### ISSUE TITLE
Add system messages

### ISSUE THREAD

**Issue by oalmajalists** [jlonge4/gpt_chatwithPDF#5]
How do you add system messages to the API code ?

**Comment by jlonge4** [comment]
@oalmajalists for logging or ?

**Comment by oalmajalists** [comment]
To have more control over the responses , by defining scope and other directions to the BOT

**Comment by oalmajalists** [comment]
I added it as below , but maybe its not the best way to do it :

sys_msgs = [
    "xxxxxx"
    "yyyyyy",
    "vvvvvv",
    "fffffff."
]

#query index using GPT
def query_index(index_to_use, query_u):
    storage_context = StorageContext.from_defaults(persist_dir=f"{PATH_TO_INDEXES}/{index_to_use}")
    index = load_index_from_storage(storage_context, service_context=service_context)
    context = "\n".join(sys_msgs)
    query_u = context + f' User: {query_u}'
    query_engine = index.as_query_engine()
    response_q = query_engine.query(query_u)
    response = {"indexed_doc": f"{index_to_use}",
                "response": f"{response_q}",
                "status": "completed"}
    return response
